### ISSUE TITLE
How to change number color

### ISSUE THREAD

**Issue by jonalxh** [web-mech/vue-css-percentage-circle#1]
Hi, thanks for this useful component.

I was trying to change the number color but I was not able to achieve it, I've tried the following:

`<PercentageCircle :percent="feedback.score" active-color="blue" complete-color="green"  id="percentage-circle" style="color: black"/>`

I've set the color in style property, assigned color from CSS with `!important` and non of them worked.

I hope you can help me and is a good idea to add  a Vue prop to change the color dynamically.

**Comment by commanddotcom** [comment]
I think it is not about `color` but about `border-color` attribute. 

Any you are right, I'm not getting the idea of pre-defined colors anyway. I would expect them to be set with `style` attribute inside the template as you do.
